id: P000364
initial_creation_type: ocr
created_at: 16/03/2020
last_modified_at: 2021-12-16 15:36:05.278986
source_metadata:
  id: bdr:W1PD53276
  title: བོད་ཀྱི་ལོ་རྒྱུས་ལ་དབྱེ་ཞིབ་བྱས་པའི་ཐོག་མའི་དཔྱད་གཏམ
  author: ''
  volumes:
    30bc8615ab854ef3b7a71b2e385e882d:
      image_group_id: I1PD54416
      title: Volume 1 of bod kyi lo rgyus la dbye zhib byas pa'i thog ma'i dpyad gtam
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
